FROM manimcommunity/manim

USER root

# RUN apt-get update \
#     && apt-get install -y --no-install-recommends \
#         sudo \
#         zsh

# COPY .devcontainer/.zshrc /home/.zshrc

USER manimuser
